
package org.rasea.agent.demoiselle.internal.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccessControl_v1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccessControlV1 {


    /**
     * 
     * @param authenticate
     * @return
     *     returns boolean
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "authenticated", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "authenticated")
    public boolean authenticate(
        @WebParam(name = "authenticate", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "authenticate")
        Credentials authenticate)
        throws WebServiceFault
    ;

    /**
     * 
     * @param rolePermissions
     * @param arg1
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.PermissionsResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "permissions", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "permissions")
    public PermissionsResponse rolePermissions(
        @WebParam(name = "rolePermissions", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "rolePermissions")
        RoleNameRequest rolePermissions,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param changePassword
     * @return
     *     returns boolean
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "changed", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "changed")
    public boolean changePassword(
        @WebParam(name = "changePassword", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "changePassword")
        NewPasswordRequest changePassword,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param listUsers
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.UsersResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "users", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "users")
    public UsersResponse listUsers(
        @WebParam(name = "listUsers", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "listUsers")
        EmptyRequest listUsers,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param listRoles
     * @param arg1
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.RolesResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "roles", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "roles")
    public RolesResponse listRoles(
        @WebParam(name = "listRoles", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "listRoles")
        ApplicationNameRequest listRoles,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param resetPassword
     * @return
     *     returns boolean
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "reseted", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "reseted")
    public boolean resetPassword(
        @WebParam(name = "resetPassword", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "resetPassword")
        ResetPasswordRequest resetPassword)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param userPermissions
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.PermissionsResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "permissions", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "permissions")
    public PermissionsResponse userPermissions(
        @WebParam(name = "userPermissions", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "userPermissions")
        UserNameRequest userPermissions,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param assignedRoles
     * @param arg1
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.RolesResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "roles", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "roles")
    public RolesResponse assignedRoles(
        @WebParam(name = "assignedRoles", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "assignedRoles")
        UserNameRequest assignedRoles,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param assignedUsers
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.UsersResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "users", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "users")
    public UsersResponse assignedUsers(
        @WebParam(name = "assignedUsers", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "assignedUsers")
        RoleNameRequest assignedUsers,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param requestConfirmationCode
     * @return
     *     returns boolean
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "requested", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "requested")
    public boolean requestConfirmationCode(
        @WebParam(name = "requestConfirmationCode", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "requestConfirmationCode")
        SimpleUserNameRequest requestConfirmationCode)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param roleDetail
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.RoleType
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "role", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "role")
    public RoleType roleDetail(
        @WebParam(name = "roleDetail", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "roleDetail")
        RoleNameRequest roleDetail,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param roleOperationsOnResource
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.OperationsResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "operations", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "operations")
    public OperationsResponse roleOperationsOnResource(
        @WebParam(name = "roleOperationsOnResource", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "roleOperationsOnResource")
        ResourceRoleRequest roleOperationsOnResource,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param unassignedRoles
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.RolesResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "roles", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "roles")
    public RolesResponse unassignedRoles(
        @WebParam(name = "unassignedRoles", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "unassignedRoles")
        UserNameRequest unassignedRoles,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param userDetail
     * @param arg1
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.UserType
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "user")
    public UserType userDetail(
        @WebParam(name = "userDetail", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "userDetail")
        SimpleUserNameRequest userDetail,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param userOperationsOnResource
     * @return
     *     returns org.rasea.agent.demoiselle.internal.proxy.OperationsResponse
     * @throws WebServiceFault
     */
    @WebMethod
    @WebResult(name = "operations", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "operations")
    public OperationsResponse userOperationsOnResource(
        @WebParam(name = "userOperationsOnResource", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", partName = "userOperationsOnResource")
        UserResourceRequest userOperationsOnResource,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/AccessControl_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

}
