
package org.rasea.agent.demoiselle.internal.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Management_v1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManagementV1 {


    /**
     * 
     * @param arg1
     * @param addUser
     * @throws WebServiceFault
     */
    @WebMethod
    public void addUser(
        @WebParam(name = "addUser", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "addUser")
        UserRequest addUser,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param addRole
     * @throws WebServiceFault
     */
    @WebMethod
    public void addRole(
        @WebParam(name = "addRole", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "addRole")
        RoleRequest addRole,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param deleteUser
     * @throws WebServiceFault
     */
    @WebMethod
    public void deleteUser(
        @WebParam(name = "deleteUser", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "deleteUser")
        SimpleUserNameRequest deleteUser,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param enableUser
     * @throws WebServiceFault
     */
    @WebMethod
    public void enableUser(
        @WebParam(name = "enableUser", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "enableUser")
        SimpleUserNameRequest enableUser,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param disableUser
     * @param arg1
     * @throws WebServiceFault
     */
    @WebMethod
    public void disableUser(
        @WebParam(name = "disableUser", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "disableUser")
        SimpleUserNameRequest disableUser,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param deleteRole
     * @param arg1
     * @throws WebServiceFault
     */
    @WebMethod
    public void deleteRole(
        @WebParam(name = "deleteRole", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "deleteRole")
        RoleNameRequest deleteRole,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param grantPermission
     * @throws WebServiceFault
     */
    @WebMethod
    public void grantPermission(
        @WebParam(name = "grantPermission", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "grantPermission")
        GrantPermissionRequest grantPermission,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param revokePermission
     * @throws WebServiceFault
     */
    @WebMethod
    public void revokePermission(
        @WebParam(name = "revokePermission", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "revokePermission")
        AuthorizationRequest revokePermission,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param assignUser
     * @throws WebServiceFault
     */
    @WebMethod
    public void assignUser(
        @WebParam(name = "assignUser", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "assignUser")
        UserRoleRequest assignUser,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param deassignUser
     * @throws WebServiceFault
     */
    @WebMethod
    public void deassignUser(
        @WebParam(name = "deassignUser", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "deassignUser")
        UserRoleRequest deassignUser,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param disableRole
     * @throws WebServiceFault
     */
    @WebMethod
    public void disableRole(
        @WebParam(name = "disableRole", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "disableRole")
        RoleNameRequest disableRole,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

    /**
     * 
     * @param arg1
     * @param enableRole
     * @throws WebServiceFault
     */
    @WebMethod
    public void enableRole(
        @WebParam(name = "enableRole", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", partName = "enableRole")
        RoleNameRequest enableRole,
        @WebParam(name = "arg1", targetNamespace = "http://rasea.org/ps/wsdl/Management_v1", header = true, partName = "arg1")
        Credentials arg1)
        throws WebServiceFault
    ;

}
