
package org.rasea.agent.demoiselle.internal.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "WebServiceFault", targetNamespace = "http://rasea.org/http://rasea.org/ps/wsdl/WebServiceException_v1")
public class WebServiceFault
    extends Exception
{

	private static final long serialVersionUID = 1L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WebServiceFaultBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WebServiceFault(String message, WebServiceFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WebServiceFault(String message, WebServiceFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.rasea.agent.demoiselle.internal.proxy.WebServiceFaultBean
     */
    public WebServiceFaultBean getFaultInfo() {
        return faultInfo;
    }

}
